config/routes.rb
Rails.application.routes.draw do
  resources :platforms
  resources :events
  resources :boards
  resources :webtoons
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get '/boards/:id', to: 'boards#index', as: 'board_index'
	get '/events/:id', to: 'events#index', as: 'event_index'
	
	root 'webtoons#index'
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(platform_params)
	user_id = @platform.user_id
	event_id = @platform.event_id
	@event_overlap = Platform.where(user_id: user_id, event_id: event_id).size
    respond_to do |format|
      
	  if @event_overlap > 0
		  format.html{redirect_to events_path, notice: '이 이벤트는 이미 신청하였습니다.'}
	  elsif @platform.save
		  format.html { redirect_to @platform, notice: '이벤트 신청이 성공되었습니다.' }
		  format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1
  # PATCH/PUT /platforms/1.json
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { render :show, status: :ok, location: @platform }
      else
        format.html { render :edit }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url, notice: 'Platform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def platform_params
      params.require(:platform).permit(:user_id, :event_id)
    end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<%= form_with(model: platform, local: true) do |form| %>
  <% if platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% platform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>매치된 이벤트</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>이벤트</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platforms.each do |platform| %>
      <tr>
        <td><%= platform.user.email %></td>
        <td><%= platform.event.event_name %></td>
        <td><%= link_to 'Show', platform %></td>
        <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
        <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>
	<%= link_to 'New Platform', new_platform_path %>
</p>

<%= link_to '이벤트로 이동', events_path %>

app/views/platforms/new.html.erb
<h1>New Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @platform.user.email %> 유저가 <%= @platform.event.event_name %>를 신청하였습니다.
</p>




<%= link_to 'Back', events_path %>