config/routes.rb
Rails.application.routes.draw do
  resources :platforms
  resources :events
  resources :boards
  resources :webtoons
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get '/boards/:id', to: 'boards#index', as: 'board_index'
	get '/events/:id', to: 'events#index', as: 'event_index'
	
	root 'webtoons#index'
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  belongs_to :webtoon
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
	user_id = @board.user_id
	webtoon_id = @board.webtoon_id
	@webtoon_overlap = Board.where(user_id: user_id, webtoon_id: webtoon_id).size
    respond_to do |format|
      if @webtoon_overlap > 0
		  format.html{redirect_to webtoons_path, notice: '이미 구독한 작품입니다.'}
	  elsif @board.save
		  format.html { redirect_to @board, notice: '보관함에 추가 되었습니다.' }
		  format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: '구독을 취소하였습니다.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:user_id, :webtoon_id)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :webtoon_id %>
    <%= form.text_field :webtoon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>보관함</h1>

<table class="table table-boarded">
  <thead>
    <tr>
      <th>구독한 웹툰</th>
      <th>id</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.webtoon.webtoon_name %></td>
        <td><%= board.user.email %></td>
        <td><%= link_to '상세정보', board %></td>
        <td><%= link_to '구독취소', board, method: :delete, data: { confirm: '구독을 취소하시겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<ul>
	<p>
		<%= link_to '웹툰사이트', webtoons_path %>
	</p>
	<p>
		<%= link_to '이벤트 확인', events_path %>
	</p>
	
</ul>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>유저:</strong>
  <%= @board.user.email %>
</p>

<p>
  <strong>웹툰:</strong>
  <%= @board.webtoon.webtoon_name %>
</p>

<p>
  <strong>구독일자:</strong>
  <%= @board.updated_at %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>