config/routes.rb
Rails.application.routes.draw do
  resources :platforms
  resources :events
  resources :boards
  resources :webtoons
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get '/boards/:id', to: 'boards#index', as: 'board_index'
	get '/events/:id', to: 'events#index', as: 'event_index'
	
	root 'webtoons#index'
end

app/models/webtoon.rb
class Webtoon < ApplicationRecord
	has_many :boards
	has_many :users, :through => :boards
end

app/controllers/webtoons_controller.rb
class WebtoonsController < ApplicationController
  before_action :set_webtoon, only: [:show, :edit, :update, :destroy]

  # GET /webtoons
  # GET /webtoons.json
  def index
    @webtoons = Webtoon.all
  end

  # GET /webtoons/1
  # GET /webtoons/1.json
  def show
  end

  # GET /webtoons/new
  def new
    @webtoon = Webtoon.new
  end

  # GET /webtoons/1/edit
  def edit
  end

  # POST /webtoons
  # POST /webtoons.json
  def create
    @webtoon = Webtoon.new(webtoon_params)

    respond_to do |format|
      if @webtoon.save
        format.html { redirect_to @webtoon, notice: 'Webtoon was successfully created.' }
        format.json { render :show, status: :created, location: @webtoon }
      else
        format.html { render :new }
        format.json { render json: @webtoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webtoons/1
  # PATCH/PUT /webtoons/1.json
  def update
    respond_to do |format|
      if @webtoon.update(webtoon_params)
        format.html { redirect_to @webtoon, notice: 'Webtoon was successfully updated.' }
        format.json { render :show, status: :ok, location: @webtoon }
      else
        format.html { render :edit }
        format.json { render json: @webtoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webtoons/1
  # DELETE /webtoons/1.json
  def destroy
    @webtoon.destroy
    respond_to do |format|
      format.html { redirect_to webtoons_url, notice: 'Webtoon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webtoon
      @webtoon = Webtoon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webtoon_params
      params.require(:webtoon).permit(:writer, :webtoon_name, :gerne)
    end
end

app/helpers/webtoons_helper.rb
module WebtoonsHelper
end

app/views/webtoons/_form.html.erb
<%= form_with(model: webtoon, local: true) do |form| %>
  <% if webtoon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webtoon.errors.count, "error") %> prohibited this webtoon from being saved:</h2>

      <ul>
      <% webtoon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :writer %>
    <%= form.text_field :writer %>
  </div>

  <div class="field">
    <%= form.label :webtoon_name %>
    <%= form.text_field :webtoon_name %>
  </div>

  <div class="field">
    <%= form.label :gerne %>
    <%= form.text_field :gerne %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webtoons/edit.html.erb
<h1>Editing Webtoon</h1>

<%= render 'form', webtoon: @webtoon %>

<%= link_to 'Show', @webtoon %> |
<%= link_to 'Back', webtoons_path %>

app/views/webtoons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>웹툰</h1>

<table class="table table-boarded">
  <thead>
    <tr>
      <th>작가명</th>
      <th>웹툰</th>
      <th>장르</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @webtoons.each do |webtoon| %>
      <tr>
        <td><%= webtoon.writer %></td>
        <td><%= webtoon.webtoon_name %></td>
        <td><%= webtoon.gerne %></td>
        <td><%= button_to "웹툰구독", boards_path(board: { user_id: current_user.id, webtoon_id: webtoon.id}) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<ul>
	<p>
		<%= link_to '이벤트 확인', events_path %>
	</p>
</ul>

app/views/webtoons/new.html.erb
<h1>New Webtoon</h1>

<%= render 'form', webtoon: @webtoon %>

<%= link_to 'Back', webtoons_path %>

app/views/webtoons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Writer:</strong>
  <%= @webtoon.writer %>
</p>

<p>
  <strong>Webtoon name:</strong>
  <%= @webtoon.webtoon_name %>
</p>

<p>
  <strong>Gerne:</strong>
  <%= @webtoon.gerne %>
</p>

<%= link_to 'Edit', edit_webtoon_path(@webtoon) %> |
<%= link_to 'Back', webtoons_path %>